
sudo: required
dist: trusty
language: go 
go:
- 1.6
- 1.7
- tip

before_install:
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
    - go get golang.org/x/tools/cmd/goimports
    - go get github.com/mattn/goveralls
    
install:
    - go get github.com/yannisl/gotex/tabular
    - go get github.com/yannisl/gotex/enviro
    - go get github.com/yannisl/gotex/mwe

script:
    - go test -coverprofile=coverage.txt -covermode=atomic ./tabular
    - go test -coverprofile=coverage.txt -covermode=atomic ./enviro
    - pdflatex mwe.tex -interaction=nonstopmode

notifications:
  email: false

 
after_success:
    - bash <(curl -s https://codecov.io/bash)
